# Generated by Django 4.1.6 on 2023-03-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customabstractbaseuser",
            name="username",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
