# Generated by Django 4.1.6 on 2023-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customabstractuser",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customabstractuser",
            name="password2",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customabstractuser",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
