# Generated by Django 4.1.6 on 2023-03-19 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customabstractuser_password_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customabstractuser",
            options={},
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="customabstractuser",
            name="user_permissions",
        ),
    ]
