# Generated by Django 4.1.6 on 2023-03-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("bookmarkList", "0002_alter_bookmark_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="users.customabstractbaseuser",
            ),
        ),
    ]
